version: '3.8'

services:
  postgres:
    image: postgres
    user: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 2

  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 2

  django:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "poetry run python manage.py migrate && poetry run python manage.py createadminuser && poetry run python manage.py runhabrparser &&poetry run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: sh -c "curl -f http://localhost:8000/"
      interval: 15s
      timeout: 5s
      retries: 3

  celery:
    build: .
    env_file:
      - .env
    command: celery -A config worker -l INFO
    depends_on:
      django:
        condition: service_healthy

  celery_beat:
    build: .
    env_file:
      - .env
    command: celery -A config beat -l INFO -S django
    depends_on:
      django:
        condition: service_healthy
